services:
  telegram-to-trmnl:
    build: ./src/.
    image: telegram-to-trmnl
    env_file:
      - ./src/.env
    # Mount source files but preserve installed packages
    environment:
      # Suppress UV hardlink warning
      - UV_LINK_MODE=copy
    # Or inject/override individual vars:
    # environment:
    #   TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    #   TRMNL_PLUGIN_UUID:  "${TRMNL_PLUGIN_UUID}"
    restart: unless-stopped