services:
  telegram-to-trmnl:
    build: .
    image: telegram-to-trmnl
    env_file:
      - .env
    # Mount source files but preserve installed packages
    volumes:
      - ./main.py:/app/main.py
      - ./bot_utils.py:/app/bot_utils.py
      - ./pdf_utils.py:/app/pdf_utils.py
      - ./epub_utils.py:/app/epub_utils.py
      - ./trmnl_utils.py:/app/trmnl_utils.py
      - ./shared.liquid:/app/shared.liquid
      - ./markup:/app/markup
    environment:
      # Suppress UV hardlink warning
      - UV_LINK_MODE=copy
    # Or inject/override individual vars:
    # environment:
    #   TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
    #   TRMNL_PLUGIN_UUID:  "${TRMNL_PLUGIN_UUID}"
    restart: unless-stopped